{% set version = "0.2.1" %}

package:
  name: isolearn
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/isolearn/isolearn-{{ version }}.tar.gz
  sha256: d0feaa7de079e360e01e9ac65f8197325aeec2bd126c0d0725f13b8ea46187b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - keras
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - isolearn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/johli/isolearn
  summary: Keras Genomics Data Generators
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
